---
all:
  hosts:
    jenkins:
      ansible_host: 192.168.77.11
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_private_key_file: "/tmp/jenkins_key"
    sonar:
      ansible_host: 192.168.77.22
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_private_key_file: "/tmp/sonar_key"