---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_package: "docker-ce"
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# Docker Compose options.
docker_compose_version: "1.24.1"
docker_compose_path: /usr/local/bin/docker-compose

# A list of users who will be added to the docker group.
docker_users: []