---

- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to start up
  uri:
    url: "http://localhost:{{ jenkins_http_port }}/cli/"
    status_code: 200
  register: result
  until: result is succeeded 
  retries: 10
  delay: 20