---
  
- name: Install utility packages common to all hosts
  apt:
    name:
    - zip
    - unzip
    - git
    - wget
    - software-properties-common
    - curl
    state: present
    autoclean: yes