---

#sudo apt-get remove docker docker-engine docker.io docker-ce
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - docker-ce
    state: absent

#sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  ignore_errors: true

#sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

#sudo apt install -y docker-ce
- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: present
  notify: restart docker

#sudo docker run hello-world
- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- include_tasks: compose.yml

- include_tasks: users.yml
  when: docker_users | length > 0